version: '3.3'
services:
  react-service:
    container_name: react-service
    build: ./
    ports:
      - '3333:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
    volumes:
      - './:/code'
      - '/code/node_modules'
